---
services:
  publisher:
    git_url: git@github.com:kamerblauwlicht/training-analytics-webinar.git
    git_branch: master
    build_root: packages
    dockerfile_path: publisher/Dockerfile
    env_vars:
      PORT: 3000
      RABBITMQ_URL: rabbitmq.cloud66.local
    ports:
    - 3000:80:443
  subscriber:
    git_url: git@github.com:kamerblauwlicht/training-analytics-webinar.git
    git_branch: master
    build_root: packages
    dockerfile_path: subscriber/Dockerfile
    env_vars:
      RABBITMQ_URL: rabbitmq.cloud66.local
databases:
- rabbitmq
